## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
!pip install gmaps

Requirement already satisfied: gmaps in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (0.9.0)
Requirement already satisfied: geojson>=2.0.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (2.5.0)
Requirement already satisfied: traitlets>=4.3.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (5.1.1)
Requirement already satisfied: six in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (1.16.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (7.31.1)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (7.6.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (3.0.20)
Requirement already satisfied: decorator in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (5.1.1)
Requirement already satisfied: pygments in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (2.11.2)
Requirement already satisfied: setuptools>=18.5 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (61.2.0)
Requirement already satisfied: colorama in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.4.4)
Requirement already satisfied: matplotlib-inline in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: jedi>=0.16 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.18.1)
Requirement already satisfied: pickleshare in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: backcall in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.0)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (6.9.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: nest-asyncio in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.5)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.12)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.8.3)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (4.9.2)
Requirement already satisfied: pyzmq>=13 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (22.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.2)
Requirement already satisfied: pywin32>=1.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (302)
Requirement already satisfied: jsonschema>=2.6 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.4.0)
Requirement already satisfied: fastjsonschema in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (2.15.1)
Requirement already satisfied: typing-extensions in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.1.1)
Requirement already satisfied: importlib-metadata in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.11.3)
Requirement already satisfied: importlib-resources>=1.4.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (5.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.18.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from importlib-resources>=1.4.0->jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.7.0)
Requirement already satisfied: wcwidth in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.8)
Requirement already satisfied: prometheus-client in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.8.0)
Requirement already satisfied: nbconvert in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.4)
Requirement already satisfied: jinja2 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.3)
Requirement already satisfied: argon2-cffi in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.15.0)
Requirement already satisfied: pycparser in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.21)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.0.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.13)
Requirement already satisfied: beautifulsoup4 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.11.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: bleach in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: defusedxml in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: testpath in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.0)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from beautifulsoup4->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.3.1)
Requirement already satisfied: packaging in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3)
Requirement already satisfied: webencodings in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\richard pamintuan\anaconda3\envs\pythondata\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.0.4)

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:/Users/Richard Pamintuan/Documents/Data Analyst Class Docs/Class Folder/World_Weather_Analysis/Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Nishihara,JP,26.1842,127.7558,81.68,89,20,4.61,few clouds
1,1,Alofi,NU,-19.0595,-169.9187,75.09,88,40,11.50,scattered clouds
2,2,Dikson,RU,73.5069,80.5464,42.71,87,72,7.83,broken clouds
3,3,Codrington,AU,-38.2667,141.9667,54.66,72,79,20.60,broken clouds
4,4,Olinda,BR,-8.0089,-34.8553,76.73,83,75,5.75,broken clouds

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip?"))
max_temp = float(input("What is your desired maximum temperature for your trip?"))

What is your desired minimum temperature for your trip?70
What is your desired maximum temperature for your trip?96

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Nishihara,JP,26.1842,127.7558,81.68,89,20,4.61,few clouds
1,1,Alofi,NU,-19.0595,-169.9187,75.09,88,40,11.50,scattered clouds
4,4,Olinda,BR,-8.0089,-34.8553,76.73,83,75,5.75,broken clouds
6,6,Rikitea,PF,-23.1203,-134.9692,72.14,77,83,21.72,light rain
8,8,Mangai,CD,-4.0500,19.5333,79.48,50,90,3.00,overcast clouds
17,17,Umm Lajj,SA,25.0213,37.2685,87.57,48,41,2.62,scattered clouds
18,18,Albany,US,42.6001,-73.9662,88.57,49,24,1.01,few clouds
21,21,Ribeira Grande,PT,38.5167,-28.7000,75.60,83,75,8.05,broken clouds
25,25,Pringsewu,ID,-5.3582,104.9744,73.26,97,98,2.35,overcast clouds
27,27,Puerto Escondido,MX,15.8500,-97.0667,87.55,65,31,6.71,scattered clouds

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Nishihara,JP,26.1842,127.7558,81.68,89,20,4.61,few clouds
1,1,Alofi,NU,-19.0595,-169.9187,75.09,88,40,11.50,scattered clouds
4,4,Olinda,BR,-8.0089,-34.8553,76.73,83,75,5.75,broken clouds
6,6,Rikitea,PF,-23.1203,-134.9692,72.14,77,83,21.72,light rain
8,8,Mangai,CD,-4.0500,19.5333,79.48,50,90,3.00,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
695,695,Pasighat,IN,28.0667,95.3333,77.52,87,98,2.48,overcast clouds
697,697,Rayachoti,IN,14.0500,78.7500,79.54,78,97,1.99,overcast clouds
698,698,Mahon,ES,39.8885,4.2658,79.36,53,0,0.00,clear sky
699,699,Salinopolis,BR,-0.6136,-47.3561,81.23,78,14,14.14,few clouds
700,700,Kisangani,CD,0.5167,25.2000,72.99,80,62,0.54,broken clouds

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Nishihara,JP,81.68,few clouds,26.1842,127.7558,
1,Alofi,NU,75.09,scattered clouds,-19.0595,-169.9187,
4,Olinda,BR,76.73,broken clouds,-8.0089,-34.8553,
6,Rikitea,PF,72.14,light rain,-23.1203,-134.9692,
8,Mangai,CD,79.48,overcast clouds,-4.0500,19.5333,
17,Umm Lajj,SA,87.57,scattered clouds,25.0213,37.2685,
18,Albany,US,88.57,few clouds,42.6001,-73.9662,
21,Ribeira Grande,PT,75.60,broken clouds,38.5167,-28.7000,
25,Pringsewu,ID,73.26,overcast clouds,-5.3582,104.9744,
27,Puerto Escondido,MX,87.55,scattered clouds,15.8500,-97.0667,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found...Skipping.")

Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.

In [11]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Nishihara,JP,81.68,few clouds,26.1842,127.7558,Minshuku Agaihama
1,Alofi,NU,75.09,scattered clouds,-19.0595,-169.9187,Taloa Heights
4,Olinda,BR,76.73,broken clouds,-8.0089,-34.8553,Flat Quatro Rodas Olinda
6,Rikitea,PF,72.14,light rain,-23.1203,-134.9692,People ThankYou
17,Umm Lajj,SA,87.57,scattered clouds,25.0213,37.2685,Moon light Furnished Units

In [12]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [13]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))